### ISSUE TITLE
Revert Docker puppeteer changes once Alpine Linux bug is fixed

### ISSUE THREAD

**Issue by mfix22** [dawnlabs/carbon#451]
Alpine Linux Bug causing Puppeteer errors: https://github.com/GoogleChrome/puppeteer/issues/3019

**TODO**:
- [x] change all the `v3.8` -> `next` in Dockefile
- [x] server.js:` args: ['--no-sandbox', '--disable-setuid-sandbox']`
- [x] `yarn add puppeteer@1.4.0`
- [x] image handler: `(target || document) -> target`
